version: '3.8'

services:
  pgvector-db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    container_name: pgvector-db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgvector
    ports:
      - "5438:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped